NewsLetter/Web/NewsLetter.MVC/Controllers/ArticleController.cs
using Bytes2you.Validation;
using Microsoft.AspNet.Identity;
using NewsLetter.Models.DbModels;
using NewsLetter.Services.Data.Contracts;
using NewsLetter.Services.Providers.Contracts;
using NewsLetter.ViewModels.Articles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsLetter.MVC.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService articleService;
        private readonly IMappingProvider mappingProvider;

        public ArticleController(IArticleService articleService, IMappingProvider mappingProvider)
        {
            Guard.WhenArgument(articleService, nameof(articleService)).IsNull().Throw();
            Guard.WhenArgument(mappingProvider, nameof(mappingProvider)).IsNull().Throw();

            this.articleService = articleService;
            this.mappingProvider = mappingProvider;
        }

        public ActionResult Index(int id)
        {
            var model = this.articleService.GetArticleById(id);

            return View(model);
        }

        public ActionResult GetArticleComments(int id)
        {
            var model = this.articleService.GetArticleComments(id);

            return this.PartialView("_CommentsPartial", model);
        }

        public ActionResult AddCommentToArtile()
        {
            return this.PartialView("_PostCommentPartial");
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCommentToArtile(int articleId, CommentViewModel comment)
        {
            var commentToAdd = this.mappingProvider.Map<CommentViewModel, Comment>(comment);
            commentToAdd.ArticleId = articleId;
            commentToAdd.UserId = this.User.Identity.GetUserId();

            this.articleService.AddCommentToArticle(commentToAdd);

            return this.GetArticleComments(articleId);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCommentReply(int articleId, int commentId, CommentReplyViewModel comment)
        {
            var commentToAdd = this.mappingProvider.Map<CommentReplyViewModel, CommentReply>(comment);
            commentToAdd.CommentId = commentId;
            commentToAdd.UserId = this.User.Identity.GetUserId();

            this.articleService.AddCommentReply(commentToAdd);

            return this.GetArticleComments(articleId);
        }
    }
}

NewsLetter/Web/NewsLetter.MVC/Controllers/CategoryController.cs
using Bytes2you.Validation;
using NewsLetter.Services.Data.Contracts;
using NewsLetter.Services.Providers.Contracts;
using NewsLetter.ViewModels.Articles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsLetter.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            Guard.WhenArgument(categoryService, nameof(categoryService)).IsNull().Throw();

            this.categoryService = categoryService;
        }

        public ActionResult Index(string category, int pageNumber, int pageSize)
        {
            var skip = (pageNumber - 1) * pageSize;
            var Take = pageSize;

            var articlesByCategory = this.categoryService.GetArticleByCategory(category);
            var articlesCount = articlesByCategory.Count() / pageSize;
            var pagedArticles = articlesByCategory.Skip(skip).Take(Take);

            if (articlesCount < 1)
            {
                articlesCount = 1;
            }

            var ArticlesByCategoryViewModel = new ArticleAndCategoryViewModel()
            {
                ArticlesByCategory = pagedArticles,
                CategoryName = category,
                ArticlesCount = articlesCount,
                pageNumber = pageNumber,
                pageSize = pageSize
            };

            return View(ArticlesByCategoryViewModel);
        }
    }
}

NewsLetter/Web/NewsLetter.MVC/Views/Shared/_CommentsPartial.cshtml
@model IEnumerable<CommentViewModel>

<div class="comments-count">
    @Model.Count() COMMENTS
</div>

<div class="comments-list-container">
    @foreach (var comment in Model)
            {
        <div class="comments-list-item row no-gutters">
            <div class="col- comment-item-info">
                <div class="comment-item-image-container">
                    <img class="comment-author-avatar" src="@comment.Author.AvatarPictureUrl">
                    <div class="comment-date">
                        <span>@comment.CreatedOn.ToString("MMM").Substring(0, 3).ToUpper()</span>
                        <span>@comment.CreatedOn.Day</span>
                    </div>
                </div>
            </div>
            <div class="col- comment-item-contnet-container">
                <h4>@comment.Author.UserName</h4>
                <div class="comment-item-content">
                    @comment.Content
                </div>
            </div>
            @if (this.User.Identity.IsAuthenticated)
            {
                <input type="button" class="reply-comment-button add-comment-toggler" value="REPLY">
            }
        </div>

        <div class="reply-comment-container add-comment-toggler hidden">
            @using (Ajax.BeginForm(nameof(ArticleController.AddCommentReply),
                    "Article",
                    new { commentId = comment.Id, articleId = comment.ArticleId },
                    new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "add-comment-form", OnComplete = "clearForm" })
            )
            {
                <div>REPLY</div>

                <div class="rc-custom-form">
                    <textarea name="Content" rows="4" class="reply-textarea"></textarea>
                    <div>
                        <input type="submit" value="SUBMIT" class="custom-form-submit">
                    </div>
                </div>
            }
        </div>

        foreach (var reply in comment.Replies)
        {
            <div class="replied-comments-list-item row no-gutters">
                <div class="col- replied-comment-item-info">
                    <div class="replied-comment-item-image-container">
                        <img class="comment-author-avatar" src="@reply.Author.AvatarPictureUrl">
                        <div class="comment-date">
                            <span>@reply.CreatedOn.ToString("MMM").Substring(0, 3).ToUpper()</span>
                            <span>@reply.CreatedOn.Day</span>
                        </div>
                    </div>
                </div>
                <div class="col- replied-comment-item-contnet-container">
                    <h4>@reply.Author.UserName</h4>
                    <div class="replied-comment-item-content">
                        @reply.Content
                    </div>
                </div>
            </div>
        }
    }
</div>
<script>
    $('.reply-comment-button').on('click', function () {
        console.log('here')
        $('.reply-comment-container').addClass('hidden');
        $(this).parent('.comments-list-item').next('div.reply-comment-container').removeClass('hidden');
    });
</script>

NewsLetter/Web/NewsLetter.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta property="og:description" content="News Letter" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>NewsLetter</title>
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <div class="logo-holder">
            <a href="/home?pageNumber=1&pageSize=5"><img src="../../Images/Static/logo.png" /></a>
        </div>
        <nav class="navbar navbar-toggleable-lg navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link nav-link-active" href="/home?pageNumber=1&pageSize=5">HOME</a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("ENTERTAINMENT", nameof(CategoryController.Index), "Category", new { category = "entertainment", pageNumber = 1, pageSize = 5 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("SPORT", nameof(CategoryController.Index), "Category", new { category = "sport", pageNumber = 1, pageSize = 5 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("POLITICS", nameof(CategoryController.Index), "Category", new { category = "politics", pageNumber = 1, pageSize = 5 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("HEALTH", nameof(CategoryController.Index), "Category", new { category = "health", pageNumber = 1, pageSize = 5 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("TECHNOLOGY", nameof(CategoryController.Index), "Category", new { category = "technology", pageNumber = 1, pageSize = 5 }, new { @class = "nav-link" })
                    </li>
                    @if (!this.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("REGISTER", nameof(AccountController.Register), "Account", "", new { @class = "nav-link nav-link-user-control" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("LOGIN", nameof(AccountController.Login), "Account", "", new { @class = "nav-link nav-link-user-control" })
                        </li>
                    }
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("ADMIN", "Index", "Admin", null, new { @class = "nav-link" })
                        </li>
                    }
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">LOGOUT</a>
                            </li>
                        }

                    }

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="search-box mr-sm-2" id="search-box" type="text" placeholder="Search this website...">
                </form>
            </div>
        </nav>
    </header>

    <main id="content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </main>

   @Scripts.Render("~/bundles/jquery")
        @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

NewsLetter/Web/NewsLetter.MVC/Views/Shared/_PostCommentPartial.cshtml
@using (Ajax.BeginForm(nameof(ArticleController.AddCommentToArtile),
                "Article",
                new { articleId = this.Request.Url.Segments[3] },
                new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "add-comment-form", OnComplete = "clearForm" })
                )
{
    <div>LEAVE A COMMENT</div>
    <div class="rc-custom-form">
        <textarea name="content" id="comment-box" rows="8"></textarea>
        <div>
            <input type="submit" id="submit-comment" value="SUBMIT">
        </div>
    </div>
}